### ISSUE TITLE
404 not found : aws-quickstart/quickstart-sap-hana-ha.git 

### ISSUE THREAD

**Issue by giuliocalzolari** [aws-quickstart/quickstart-sap-s4-hana#5]
sap-hana-ha repository  `git@github.com:aws-quickstart/quickstart-sap-hana-ha.git` is not available, can you please double check?

**Comment by giuliocalzolari** [comment]
@k53lee

**Comment by k53lee** [comment]
Sorry for the inconvenience! We’ll inform you as soon as it’s available for download.

**Comment by k53lee** [comment]
Hi Giulio,

You should now be able to download the templates. Please feel free to let
me know if you have any questions.

Regards,

Howard

**Comment by giuliocalzolari** [comment]
Thanks
